export const MODULES = [
  {
    id: 'service-desk',
    name: 'Service Desk',
    tagline: 'Chamados com SLA e rastreabilidade',
    color: '#185FA5',
    features: ['Abertura de chamados online', 'SLA por prioridade', 'Histórico completo', 'Notificações em tempo real', 'Escalação automática'],
    desc: 'Abra, acompanhe e resolva chamados com SLA definido, prioridade clara e histórico completo de cada interação.',
    seoTitle: 'Service Desk — Chamados e SLA | Fropty Hub',
    seoDesc: 'Gerencie chamados de suporte com SLA por prioridade, histórico completo e notificações em tempo real. Incluído no Fropty Hub sem custo adicional.',
  },
  {
    id: 'projetos',
    name: 'Projetos',
    tagline: 'Visibilidade total de ponta a ponta',
    color: '#3b82f6',
    features: ['Timeline e marcos', 'Aprovações online', 'Entregas documentadas', 'Status em tempo real', 'Solicitações de mudança'],
    desc: 'Acompanhe cada etapa do projeto com timeline, marcos, aprovações e documentação de entregas — sem precisar perguntar.',
    seoTitle: 'Projetos — Visibilidade e Aprovações | Fropty Hub',
    seoDesc: 'Acompanhe projetos em tempo real com timeline, marcos e aprovações online. Clientes Fropty têm visibilidade total sem precisar perguntar.',
  },
  {
    id: 'financeiro',
    name: 'Financeiro',
    tagline: 'Faturas, contratos e NF centralizados',
    color: '#22c55e',
    features: ['Histórico de faturas', 'Download de NF', 'Contratos e propostas', 'Extratos mensais', 'Alertas de vencimento'],
    desc: 'Todas as faturas, contratos e notas fiscais em um só lugar. Sem e-mail, sem anexo perdido.',
    seoTitle: 'Financeiro — Faturas e Contratos | Fropty Hub',
    seoDesc: 'Acesse faturas, notas fiscais e contratos diretamente no portal. Histórico completo e alertas de vencimento sem depender de e-mail.',
  },
  {
    id: 'knowledge-base',
    name: 'Knowledge Base',
    tagline: 'Documentação acessível e buscável',
    color: '#EF9F27',
    features: ['Artigos por categoria', 'Busca full-text', 'Tutoriais em vídeo', 'FAQ atualizado', 'Guias de integração'],
    desc: 'Base de conhecimento completa para que o cliente resolva dúvidas sozinho antes de abrir um chamado.',
    seoTitle: 'Knowledge Base — Documentação e FAQ | Fropty Hub',
    seoDesc: 'Base de conhecimento completa com artigos, tutoriais e guias de integração. Clientes resolvem dúvidas sem precisar abrir chamados.',
  },
  {
    id: 'roadmap',
    name: 'Roadmap',
    tagline: 'Participe da evolução do produto',
    color: '#F97316',
    features: ['Roadmap público', 'Votação de features', 'Sugestões de melhoria', 'Status de entregas', 'Changelog'],
    desc: 'O cliente vê o que está sendo construído, vota em funcionalidades e acompanha o status de cada entrega.',
    seoTitle: 'Roadmap — Votação e Changelog | Fropty Hub',
    seoDesc: 'Acompanhe o roadmap do produto, vote em funcionalidades e veja o status de cada entrega. Transparência total para clientes Fropty.',
  },
  {
    id: 'customer-success',
    name: 'Customer Success',
    tagline: 'Saúde e retenção proativas',
    color: '#ef4444',
    features: ['Health score', 'NPS automatizado', 'Onboarding guiado', 'Check-ins periódicos', 'Alertas de churn'],
    desc: 'Acompanhamento proativo da saúde do cliente — health score, NPS e check-ins para antecipar problemas.',
    seoTitle: 'Customer Success — Health Score e NPS | Fropty Hub',
    seoDesc: 'Monitore a saúde de clientes com health score, NPS automatizado e alertas de churn. Retenção proativa incluída no Fropty Hub.',
  },
  {
    id: 'health-score',
    name: 'Health Score',
    tagline: 'Saiba quem está prestes a cancelar',
    color: '#22c55e',
    features: ['Score composto em tempo real', 'Alertas de churn preventivos', 'Análise de satisfação', 'Métricas de uso e engajamento', 'Análise de receita'],
    desc: 'Score composto (satisfação + tickets + uso + engajamento + receita) que avisa quando um cliente está em risco — antes de ele cancelar.',
    seoTitle: 'Health Score — Prevenção de Churn | Fropty Hub',
    seoDesc: 'Score composto em tempo real que alerta quando um cliente está em risco de cancelar. Reduza churn antes que aconteça com o Fropty Hub.',
  },
] as const

export type Module = typeof MODULES[number]
export type ModuleId = Module['id']
